### ISSUE TITLE
Проблема с синглтоном

### ISSUE THREAD

**Issue by NS823** [BasilYes/godot-yandex-games-sdk#1]
В моём проекте используется два сингл тона (SDK и Data), где все функции SDK используются в Data. Однако, при запуске проекта Data опережает SDK из-за чего выскакивают ошибки. В общем, как я считаю, следует добавить в документацию добавление сингл тона из SDK вручную во избежание излишних проблем. (Лично моё мнение)

**Comment by BasilYes** [comment]
В годоте можно поменять порядок загрузки синглонов (стрелочки с права)
![image](https://github.com/BasilYes/godot-yandex-games-sdk/assets/36816595/6faf4601-698f-4d0d-968b-dd190aab18fb)
но я еще посмотрю можно ли поставить в аддоне, что бы синглтон загружался первым в очередь

**Comment by BasilYes** [comment]
Нет нельзя, получается только менять порядок стрелочками по необходимости

**Comment by NS823** [comment]
Спасибо за ответ.

**Comment by NS823** [comment]
Ещё вопрос, не собираешься сделать плагин официальным?

**Comment by BasilYes** [comment]
Я не связывался с Яндексом по этому поводу, но мне кажется как минимум нужно будет реализовать большую часть функционала их SDK, а я сейчас занят другим. По этому нет, не собираюсь. Если тебе нужна будет какая-то функция, которая у меня не реализована, пиши сюда, сделаю или на крайний случай покажу как ее сделать самому, не то что бы это было сложно, просто требует времени. Еще можешь посмотреть на этот плагин https://github.com/instant-games-bridge/instant-games-bridge-godot , я не знал про его существование, когда делал свой.
