### ISSUE TITLE
Помогите с Head Include 

### ISSUE THREAD

**Issue by MihaSmit** [BasilYes/godot-yandex-games-sdk#13]
Какие скрипты нужны чтобы ваш аддон работал правильно? Можно ваш Head Include посмотреть скопировать)?
![изображение](https://github.com/BasilYes/godot-yandex-games-sdk/assets/16068635/2cbdb332-0b68-4ae9-a323-e08e0ef44edd)

**Comment by MihaSmit** [comment]
Ааа. понял что в фьючерс нужно просто указать yandex. плохо читал сори

**Comment by BasilYes** [comment]
Бывает, ничего страшного
