### ISSUE TITLE
Проблема инициализации игрока при вызове метода init_player()

### ISSUE THREAD

**Issue by MihaSmit** [BasilYes/godot-yandex-games-sdk#14]
У некоторых людей и в том числе у меня на втором ПК есть такая ошибка инициализации игрока:
![изображение](https://github.com/BasilYes/godot-yandex-games-sdk/assets/16068635/032874d8-1b84-4ac0-9ec4-c931d9fa1d02)
писал в тех поддержку яндекса на что посоветовали зайти в режиме инкогнито - получилось.
После чего я почистил кеш и куки но без режима инкогнито все равно выдает эту ошибку. Так же мой друг пробовал зайти в всех режимах у него тоже эта ошибка.
godot 3.5 версия аддона 0.1.1

**Comment by BasilYes** [comment]
Скинь лог по больше, у тебя половина обрезана, не знаю, что там справа написано
![image](https://github.com/BasilYes/godot-yandex-games-sdk/assets/36816595/73ff8dda-83ce-4612-b4ee-7515cc85de0a)

**Comment by BasilYes** [comment]
Еще попробуй позаходить в другие игры с СДК, там такая же ошибка?

**Comment by MihaSmit** [comment]
Привет, большое спасибо что откликнулся! Эта ошибка происходит у меня в браузере на компьютере который находится на работе. Сейчас я дома и у меня не выскакивает эта ошибка. Вот скриншот который я кидал службе поддержки яндекса
![8c4b2d42-d05e-49f9-baf4-e6075501181f](https://github.com/BasilYes/godot-yandex-games-sdk/assets/16068635/bb51c34b-8027-4eda-9bca-2be41407afdf)

больше скринов смогу сделать только завтра на работе, так как дома не могу вызвать эту ошибку. + напишу еще своему товарищу подожду, чтобы он тоже попробовал другие веб браузеры и побольше логов взял если будут ошибки.

На счет других игр - все было нормально, я пробовал заходить в другие правда не уверен был ли я в тех играх инициализирован корректно.
Моя игра же по сути тоже работает, но я без инициализации не могу брать ни данные с облака ни загружать их, ни проверять авторизован ли игрок в яндексе, ну это думаю понятно.
Еще раз спасибо за то что откликнулся, понравился твой аддон его простотой в использовании :)

**Comment by BasilYes** [comment]
Можешь попробовать посоздвать контейнеры в firefox, может поможет (но врядли). Скорее всего ошибка где-то на их стороне, гарантировать не могу, но я со своей стороны даже не знаю как это проверить, сам с багом не сталкивался, ошибка которую они тебе возвращают мне ничего не говорит (хотя есть предположение, что у тебя слишком большой пинг 
![image](https://github.com/BasilYes/godot-yandex-games-sdk/assets/36816595/bcb30949-67cc-407c-b7da-76a201e82989)
). Логи доступны на любой версии, по крайней мере ошибки он точно тебе отсыпет и на другой игре, если они будут. Проверить наличие инициализации СДК у игры можно (смотри если у нее облачные сохранения, это указано на страничке игры)

**Comment by MihaSmit** [comment]
Ну то что пинг - я сомневаюсь так как с другими играми проблем не было + с инкогнито же ошибки нет. Ох не знаю. Завтра на работе попробую конечно с контейнерами но сомневаюсь что обычные игроки будут такое проворачивать + если у моего товарища выскочила эта ошибка, то вероятность того что у игроков она будет крайне высока. 
Я вижу вариант попробовать другой сдк, может это поможет (чем, не знаю) но вдруг там эта проблема решена, отпишу позже с результатами через пару дней. (надо еще с другим сдк разобраться) но твой мне нравится больше всего за его простоту)

**Comment by BasilYes** [comment]
Тольк логи мне скинь пожалуйста

**Comment by MihaSmit** [comment]
вот полный лог
![изображение](https://github.com/BasilYes/godot-yandex-games-sdk/assets/16068635/dbb3d995-fed9-4eb7-8212-96dd9ffea20b)
![изображение](https://github.com/BasilYes/godot-yandex-games-sdk/assets/16068635/9e3ce764-be42-4157-8728-b358a051ad90)

**Comment by BasilYes** [comment]
Ничего не понял, на этом мои полномочия все, похоже на то, что яндекс отклоняет из-за "блокировки содержимого", в их документации о таком ничего нет, по этому я хз, что с этим делать. Можешь попробовать другой СДК
![image](https://github.com/BasilYes/godot-yandex-games-sdk/assets/36816595/d6b30aaa-0a9b-405e-b3c1-8f4148f7190e)
