### ISSUE TITLE
Мне нужна помощь с Яндекс sdk

### ISSUE THREAD

**Issue by capins11** [BasilYes/godot-yandex-games-sdk#16]
<img width="918" alt="Снимок экрана 2024-06-26 в 00 50 37" src="https://github.com/BasilYes/godot-yandex-games-sdk/assets/173852171/64ba890c-d8db-4e19-8c35-483618afdbf5">

Я понял как добавить сам sdk и сделал его глобальным. Но я не понимаю как использовать функции. Как показано на скрин шоте не работает. Буду очень признателен. Весь день ищу ответ на этот вопрос.

**Comment by DarlingInSteam** [comment]
Обращайся через свой singleton объект к функциям необходимым. Пример использования у тебя на 92 строке. Все аргументы, которые надо передавать в функции, написаны в Readme.

**Comment by BasilYes** [comment]
> Обращайся через свой singleton объект к функциям необходимым. Пример использования у тебя на 92 строке. Все аргументы, которые надо передавать в функции, написаны в Readme.
Да, если совсем не понятно, в ветке в которой находится плагин для третьей версии есть примеры, концеплуально при переходе не 4 ничего не изменилось

**Comment by BasilYes** [comment]
Либо пиши более конкретно вопрос (создай новый issue)
