### ISSUE TITLE
Реклама show_interstitial_ad и show_rewarded_ad.

### ISSUE THREAD

**Issue by iobda** [BasilYes/godot-yandex-games-sdk#19]
Не могли бы вы показать примеры использования, примеры возвратного сигналов signal rewarded_ad(result) и
signal interstitial_ad(result)? Какого типа result? Это string? Я не понимаю как проверить просмотр пользователем рекламы полностью.

**Comment by BasilYes** [comment]
![image](https://github.com/user-attachments/assets/d00d357b-29d5-4ae2-8d62-3ca23e730807)
Возвращает строки прямо как показано в документации

**Comment by BasilYes** [comment]
Читай пожалуйста как работают сигналы в годоте. Официальная документация в помощь.
в твоем случае
```
func _ready() -> void:
  YandexSDK.rewarded_ad.connect(rewarded)

func _reward_ad_button_press() -> void:
  YandexSDK.show_rewarded_ad()

func rewarded(result) -> void:
  if result == 'rewarded':
    first.text = 'rewarded'
```

**Comment by mrfrolic555** [comment]
На будущее кому либо если такая же проблема:
я новичок в godot, решил покопаться в том как подключиться к яндекс sdk  и как подключить rewarded рекламу по нажатии на кнопку "получить миллион долларов" (экспериментальная псевдо игра)
![image](https://github.com/user-attachments/assets/b60bca6b-611d-49d1-83a2-18e9fc9e0c1a)
нигде нет инфы по поводу godot и яндекс игры и этот аддон конечно спасение, НО

![image](https://github.com/user-attachments/assets/ba49d18a-17f2-47ee-9864-39df2795e874)
Я подключил сигнал в func _ready() 
`YandexSDK.rewarded_ad.connect(rewarded_ad_result)`
С этим кодом ничего не работало. Деньги не прибавлялись. Главное показывается реклама (то есть сама реклама при нажатии кнопки работает) но не прибавляются деньги после её окончания. Я долго ломал над этим голову. Может быть проблема в сигнале или что то?
![image](https://github.com/user-attachments/assets/8edc839b-86ff-4949-81e0-7329b2c248e9)
Потом я открыл для себя существование консоли в браузере и она начала мне говорить о том, что проблемы на 105 строчке. 
if result == 'rewarded': 

В итоге я решил проблему именно так (спасибо chatgpt):
![image](https://github.com/user-attachments/assets/35a609db-7b93-41c5-ac3a-46b53bd572fc)

То есть нужно было перевести result (который является массивом) в string (у меня это status) и после этого уже string сравнивать с 'rewarded'. Не думаю что проверка if typeof(result) == TYPE_ARRAY and result.size() > 0 обязательна, но пусть будет. Теперь показывается реклама и после окончания рекламы прибавляется нужная сумма денег. 

Короче хз была ли у кого то такая проблема или я один такой, но на всякий случай
