### ISSUE TITLE
Что-то тут не так

### ISSUE THREAD

**Issue by NS823** [BasilYes/godot-yandex-games-sdk#2]
```gdscript
func _init():
	
	YaSDK.connect("rewarded_ad", self, '_rewarded_ad_signal')
	YaSDK.connect("ad", self, '_ad_signal')
	YaSDK.connect("game_initialized", self, '_game_initialized_signal')
	
	YaSDK.init_game()
	#YaSDK.show_ad()
```
![image](https://github.com/BasilYes/godot-yandex-games-sdk/assets/86913028/87aa199a-c9c1-4ced-bd2e-297b7ee94ff1)

**Comment by BasilYes** [comment]
У тебя ошибка с сигналами, скорее всего какая-то из функций не правильная. Обрати внимание, что не которые сигналы возвращают данные в виде словаря, некоторые нет 
![image](https://github.com/BasilYes/godot-yandex-games-sdk/assets/36816595/b3bcf416-78fe-41e2-9267-6c99daf6e671)

**Comment by BasilYes** [comment]
А еще когда у тебя возникают ошибки подобного рода, пробуй А) запускать просто на компе (не в вебе) и он выведет тебе ошибку, если она не относится на прямую к Яндекс играм. Б) Читать, что за ошибки тебе выводит движок. В) Пользоваться дебагером в вебе (F12) С) Выкладывать больше информации с ошибкой (лог из дебагера на F12 и больше кода из файла где у тебя возникла ошибка)

**Comment by NS823** [comment]
Оставил только сигнал game_initialized и функция сигнала при вызове просто не реагирует. Я не могу понять инициализовался ли SDK. Может я где-то что-то не так сделал, хотя всё в функции _ready() и вначале YaSDK.init_game().

**Comment by BasilYes** [comment]
Нажми F12, плагин постоянно принтует, что и как он сделал. Подключилось сдк или нет

**Comment by NS823** [comment]
Проблема решена. Оказалось, что я не включил сам плагин /:
