### ISSUE TITLE
Звук при сворачивании

### ISSUE THREAD

**Issue by Regrad** [BasilYes/godot-yandex-games-sdk#20]
По правилам Яндекса нужно убирать звук, когда игра не в фокусе (кликнули в другое место, на другую вкладку, в другое приложение). В старой версии на 3.5 это работало (я создавал тикет на этот счёт), а в новой версии под 4.3 звук и музыка продолжают играть (возможно нужно ставить на паузу весь процесс игры при отсутствии фокуса).
Если поправишь или подскажешь как добиться этого результата - буду очень благодарен.

**Comment by BasilYes** [comment]
Используй последнюю версию плагина с гитхаба, [работает автоматически](https://github.com/BasilYes/godot-yandex-games-sdk/blob/main/yandex_sdk.gd)
Или можешь вставить в любой синглтон, если не хочешь обновлять плагин

```
func _ready() -> void:
	if is_working():
		get_window().focus_entered.connect(func() -> void:
				print("focus in signal")
				AudioServer.set_bus_mute(0, false)
		)
		get_window().focus_exited.connect(func() -> void:
				print("focus out signal")
				AudioServer.set_bus_mute(0, true)
		)
```

**Comment by Regrad** [comment]
Обновил версию с Гита. Звук заработал, но SDK перестал инициализироваться =)
