### ISSUE TITLE
Ошибка в вызове сигнала Godot 4.3 stable.

### ISSUE THREAD

**Issue by swrneko** [BasilYes/godot-yandex-games-sdk#23]
Ошибка в вызове сигнала в функции _interstitial_ad.
```
func _interstitial_ad(args) -> void:
	print("ad res: ", args[0])
	emit_signal("interstitial_ad", args)
```
строку emit_signal("interstitial_ad", args) надо исправить на emit_signal("interstitial_ad", args[0]), иначе сигнал interstitial_ad(result) не отрабатывает корректно.

Можешь просто скопировать правильную функцию ниже (протестировано и всё работает):
```
func _interstitial_ad(args) -> void:
	print("ad res: ", args[0])
	emit_signal("interstitial_ad", args[0])
```

**Comment by BasilYes** [comment]
Попробуй последний коммит

**Comment by swrneko** [comment]
Благодарю за исправление!
