### ISSUE TITLE
when ads completed cannot add rewards

### ISSUE THREAD

**Issue by kamalasim74** [BasilYes/godot-yandex-games-sdk#26]
Hi I am using this sdk for my game. When reward ads completes Rewards not added to players.
I am using this method

func _on_rewarded_ad(result: String) -> void:

	match result:

		"rewarded":
			rewardad_completed()

		"closed":
			pass
			
		"opened":
			pass
			
		"error":
			pass

func rewardad_completed()

#here is the code which add rewards

**Comment by BasilYes** [comment]
You did't say nothing useful to identify you problem. What's function it is? Do you use signal as mentioned in README?
![image](https://github.com/user-attachments/assets/4d1b008b-30e6-4a2b-87d3-c83b851664b4)

**Comment by kamalasim74** [comment]
Sorry for my English, I have implemented this sdk in my game which shows rewardAd  successfully. But the problem is when rewardAd completed now I want to give user Rewards  I am beginner in programming. I have use this method to give rewards to users when rewardAd completes 

func _ready():
        YandexSDK.rewarded_ad.connect(_on_rewarded_ad)

func _on_rewarded_ad(result: String) -> void:
	match result:
		"rewarded":
			
			rewardad_completed()
		"closed":
			pass
			
		"opened":
			pass
		
		"error":
			pass

func rewardad_completed():
	Coins += 30

**Comment by BasilYes** [comment]
Можно по русски если удобно.
Did _on_reward_ad called? Try to add print(result) to function and check it in browser debug panel (F12 button, press it before launch the game)

**Comment by kamalasim74** [comment]
Объявления показываются успешно, но не удается добавить награды пользователям после завершения рекламы.

**Comment by kamalasim74** [comment]
Можете ли вы дать мне метод, чтобы награждать игроков, когда реклама завершена?

**Comment by BasilYes** [comment]
Проверь вызывается ли у тебя функция func _ready(): и func _on_rewarded_ad(result: String) -> void:
Поставь в них какие-нибудь принты print("ready") и print(result) или что-то типа, запусти на площадке и зайди в дебаг браузера (F12 нажми) и посмотри вызываются ли эти функции

**Comment by kamalasim74** [comment]
Это правильный метод для награждения игрока? Если вы используете другой метод, пожалуйста, предоставьте ваш метод.
```

func _on_rewarded_ad(result: String) -> void:
	match result:
		"rewarded":
			rewardad_completed()
		"closed":
			pass
		"opened":
			pass
		"error":
			pass

```

**Comment by BasilYes** [comment]
Yes, I was used this call on inside _ready in my game and it's worked
```GDScript
YandexSDK.rewarded_ad.connect(func(result: String) -> void:
		if not result:
			return
		match result:
			"opened":
				pass
			"rewarded":
				reward_func()
			"closed":
				pass
			"error":
				pass
		)
```

**Comment by kamalasim74** [comment]
![SDKSS](https://github.com/user-attachments/assets/3df7042a-f9de-45ac-b634-763344afba8b)
Not working bro

**Comment by BasilYes** [comment]
TRY TO DEBUG IT PLS. Try to add print(result) to function and check it in browser debug panel (F12 button, press it before launch the game or find "developer tools" button in your browser)

**Comment by kamalasim74** [comment]
![Uploading sdk_error.png…]()

**Comment by kamalasim74** [comment]
![sdk_error](https://github.com/user-attachments/assets/6ba979e1-c2e8-4349-8f6e-dcb54cad9eaa)

**Comment by BasilYes** [comment]
get plugin from git, newer version

**Comment by kamalasim74** [comment]
ok

**Comment by BasilYes** [comment]
Did it's work?

**Comment by BasilYes** [comment]
Somehow you got older version of plugin (I checked, I'm updated it in asset lib two month ago) so resent README guide not worked

**Comment by kamalasim74** [comment]
It worked bro thanks.
