### ISSUE TITLE
Сигнал rewarded_ad никогда не возвращает rewarded

### ISSUE THREAD

**Issue by BesheniiChitak** [BasilYes/godot-yandex-games-sdk#27]
Код:
```
extends Node2D

func _ready() -> void:
	YandexSDK.init_game()
	YandexSDK.game_ready()
	
	YandexSDK.rewarded_ad.connect(ad)

func _on_ad_pressed() -> void:
	$result.text = "start"
	YandexSDK.show_rewarded_ad()
	
func ad(result) -> void:
	$result.text = result
```
Проблема:
Код устанавливает результат сигнала в текст кнопки, но даже если реклама с наградой полностью просмотрена, возвращается closed а не rewarded.
![image](https://github.com/user-attachments/assets/41bef7a2-8b0e-4234-8537-45e476fa3499)
![image](https://github.com/user-attachments/assets/a7bf169b-30a6-4495-a08a-e268ea9c1bc4)

**Comment by BasilYes** [comment]
Все просто, реклама сначала rewarded а потом closed и у тебя кнопка просто переписывает текст с rewarded на closed
