### ISSUE TITLE
Планируется ли YandexSDK для GODOT 4?

### ISSUE THREAD

**Issue by Pushiron** [BasilYes/godot-yandex-games-sdk#5]
Добрый день, планируется ли новая версия SDK для GODOT 4?

**Comment by BasilYes** [comment]
Yandex games не работают с godot 4

**Comment by BasilYes** [comment]
> Добрый день, планируется ли новая версия SDK для GODOT 4?

@Pushiron Если до сих пор интересно, плагин обновлен до godot 4.3 ипользуй версию из ветки main
