### ISSUE TITLE
Не авторизовывается игрок при вызове метода init_player()

### ISSUE THREAD

**Issue by Nahfahlaar** [BasilYes/godot-yandex-games-sdk#6]
Добрый день, при вызове метода init_player() выскакивает ошибка "не авторизован для запроса", может я не правильно вызываю, помогите пожалуйста
![Снимок экрана 2023-12-16 142746](https://github.com/BasilYes/godot-yandex-games-sdk/assets/92239305/e52f9c35-81d3-4191-9dd9-8d9e51ce4e61)
![Снимок экрана 2023-12-16 142804](https://github.com/BasilYes/godot-yandex-games-sdk/assets/92239305/ffe14281-e0b0-4086-9c4b-8cc8ddf820e7)

**Comment by BasilYes** [comment]
Ты включил пллагин?
