### ISSUE TITLE
Вопрос снова не по теме, но вот почему в html у проекта уменьшается качество, то есть спрайты сжимаются, хотя при обычном запуске проекта все нормально

### ISSUE THREAD

**Issue by Pohuy-mne** [BasilYes/godot-yandex-games-sdk#9]

**Comment by BasilYes** [comment]
Посмотри настройки сжатия Тут
![image](https://github.com/BasilYes/godot-yandex-games-sdk/assets/36816595/614bc352-d776-43ff-a471-ec492fd01778)
Тут при импорте (или по умолчанию тут)
![image](https://github.com/BasilYes/godot-yandex-games-sdk/assets/36816595/df11348e-826f-4a47-995f-96d11e4f3950)
И попробуй поиграть с галочкми тут
![image](https://github.com/BasilYes/godot-yandex-games-sdk/assets/36816595/bafcc917-050e-4e80-a7b6-a078d203835f)
А еще лучше обращатся с вопросами по годоту [сюда](https://t.me/godot_engine/218678) или в оффициальный дискорд/форум (если можешь в английский)
